#!/bin/bash
# install script for xkb wordstar keys
# Dependencies: you must be running X Windows on Linux using xkb

echo "Creating directory tree at ~/.xkb required by xkb to load files."
mkdir -p ~/.xkb/symbols
mkdir -p ~/.xkb/compat
mkdir -p ~/.local/bin
cp wordstar ~/.xkb/symbols
cp wscompat ~/.xkb/compat
cp wskeys wskeys-debug ~/.local/bin
echo "Done."

# Ask whether to make wskeys auto-load when X session starts for this user
startup_file=~/.config/autostart/WordstarKeys.desktop
if ! [[ -e "$startup_file" ]]; then
  read -p "Shall I make wskeys load with the X Windows session by adding it at "$startup_file" (y/n)? " -n1 add_at_startup
  echo
  if [[ "$add_at_startup" == "y" ]]; then
    cp WordstarKeys.desktop $startup_file
    echo "Done."
  fi
fi

# Tell the user if it needs to be added to the PATH
if [[ "$PATH" != *"$HOME/.local/bin"* ]]; then
    echo "wskeys has been added to $HOME/.local/bin, so if you want to run 'wskeys' then"
    echo "you need to add ~/.local/bin to your PATH, or on some Linux distributions"
    echo "your default ~/.profile may automatically do so on next login."
fi
