#!/bin/bash
# Print the current key map and reload with wordstar keys included
# Note: -w1 makes xkbcomp ignore warnings that are in existing keymap files.
# If you want warnings run to debug your key changes run 'wskeys -w10'
# and compare differences to find new warnings
setxkbmap -print \
| sed -E 's/(.*xkb_keycodes.*".*)(".*)/\1+wskeycodes(ws_keycodes)\2/g' \
| sed -E 's/(.*xkb_compat.*".*)(".*)/\1+ctrlmoves(ctrl_moves)\2/g' \
| sed -E 's/(.*xkb_symbols.*".*)(".*)/\1+wordstar(keys)\2/g' \
| xkbcomp -w1 -I$HOME/.xkb - $DISPLAY "$@"
